### ISSUE TITLE
Public Workspace on Postman

### ISSUE THREAD

**Issue by arlemi** [intel-secl/intel-secl#1]
Hey there! 

I just found the [public workspace you've created on Postman](https://www.postman.com/intelsecldc/workspace/intel-secl-dc-api-collections/overview) (disclaimer: I work there) and wanted to reach out mostly to say that it was great work! You've done pretty much everything we've seen our partners doing, without any help from our end.
That said I'd love to have a chat with the person who created it to discuss some automation you could be doing (e.g. linking your collections to an api specs to keep them up to date easily), show some quick tips about public workspaces in general, but also to get some feedback on your experience with public workspaces. 🙂 

You can reach out to me directly on arlemi.turpault@postman.com or let me know if there's a better way to reach out to you!

**Comment by ddhawal** [comment]
@arlemi Sure, we would reach out to you soon.

**Comment by arlemi** [comment]
@ddhawal Great to hear, looking forward to your email. :)

**Comment by arlemi** [comment]
@ddhawal Reaching out again as we're planning a featured list for security-related workspaces next week and we'd love to add your team to it. 
As we have a bunch of marketing coming out at the same time (e.g.[ a blog post](https://blog.postman.com/apis-powering-the-future-of-communications/)), it'd be worth updating your team profile with a summary for the collections, and a nice profile banner. If you need help with that let me know!

I've also tried reaching out to the person who created the workspace directly but did not get any response unfortunately.
